### ISSUE TITLE
Found no camera

### ISSUE THREAD

**Issue by Experiment4** [Billwilliams1952/PiCameraApp#18]
Hi,
i want tio use the camera for a microscope and found no other application which has an gui. so i invest some time to get this one here running. So far i managed to install tkinter and get rid of that message.
Now i am stuck at the error:

> pi@octopi:~/PiCameraApp-master/Source $ /usr/bin/python3 PiCameraApp.py
> Traceback (most recent call last):
>   File "/home/pi/PiCameraApp-master/Source/AnnotationOverlay.py", line 61, in <module>
>     import 	picamera
> ModuleNotFoundError: No module named 'picamera'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "PiCameraApp.py", line 38, in <module>
>     from	AnnotationOverlay	import *
>   File "/home/pi/PiCameraApp-master/Source/AnnotationOverlay.py", line 65, in <module>
>     raise ImportError("You do not seem to have picamera installed")
> ImportError: You do not seem to have picamera installed

I try to use it with python3 on a raspi 4 with mostly new software installed. i am also running octoprint.
i can run qtv4l2 and take videos with the cam so i can assure it is properbly connected and working. i have to stop my webcamd service to get it running and i am not sure, if picam needs webcamd running or not. But it did not make any difference regarding this stated error. 
may i be allowed one sidenote. I also investet 2hours to get a desktop icon installed (ahhrg so much time)..i don know, if this repository is still maintained, but if it is, i would like to share that with you. 
cu
thomas

**Comment by surak** [comment]
This is not related to the camera, but to the picamera module - it's explained on the readme: The python interface to the PiCamera hardware. See https://picamera.readthedocs.io/en/release-1.13/install.html
