### ISSUE TITLE
Cannot import ImageTk

### ISSUE THREAD

**Issue by lumberjackjm** [Billwilliams1952/PiCameraApp#20]
```
pi@raspberrypi:~/Desktop/PiCameraApp-master/Source $ sudo python3 PiCameraApp.py
Traceback (most recent call last):
  File "PiCameraApp.py", line 38, in <module>
    from	AnnotationOverlay	import *
  File "/home/pi/Desktop/PiCameraApp-master/Source/AnnotationOverlay.py", line 52, in <module>
    from 	Dialog	import *
  File "/home/pi/Desktop/PiCameraApp-master/Source/Dialog.py", line 43, in <module>
    from PIL import Image, ImageTk, ExifTags
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```

**Comment by bgnoronha** [comment]
Hi, I also had the same problem.
Looks like the code was only tested on python2
So when I run the code line: sudo apt-get install python3-pil.imagetk in the terminal, and then run the code, it runs normally.

I hope it helps!

**Comment by PatrichCerpa** [comment]
Thanks a lot, it works for me!

**Comment by rahulmotiyar** [comment]
After 2 hours of struggle, i landed here and i am thankful to you

**Comment by kidlat14** [comment]
> Hi, I also had the same problem. Looks like the code was only tested on python2 So when I run the code line: sudo apt-get install python3-pil.imagetk in the terminal, and then run the code, it runs normally.
> 
> I hope it helps!

OMG. I've been struggling with this exact problem for at least 5 hours. Life is kinda cruel that the answer is already here and was posted two years ago. Thank you so much!
