### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by benwood19** [Billwilliams1952/PiCameraApp#4]
Hi there,

Is there an updated version to work with the TKinter format changes for python3. I am also using a raspberry Pi 3 board if this makes a difference? Also it is saying that the PIL is missing even though I have installed it. Any help would be great.

**Comment by Billwilliams1952** [comment]
I’m getting ready to upload a new version this week. (Getting time to do it)

I’ve been running Python 2.7 but I’ll now test it under Python 3.x (latest) and let you know what I discover. I’ll also investigate the PIL problem. 

Sorry you’re having so much trouble. 

Bill

**Comment by Billwilliams1952** [comment]
Yep, lots of problems with libraries using Python3. I am going through the code and fixing the imports. 

PIL is a problem with Python 3. 

Be patient.  Bill

**Comment by Billwilliams1952** [comment]
PIL on the RPI is the PILLOW fork which should be installed. However, ImageTk under Python 3 requires a library which was not installed on my RPI. 

sudo apt-get install python3-pil.imagetk
Other code incompatibilities when moving to Python 3. Will document in the README file when the updates are uploaded to Github. 
This week!
Bill

**Comment by benwood19** [comment]
Hi there,

Sorry I haven’t replied I was on leave for my company. Thank you for putting so much effort into getting this sorted I look forward to being able to test it out.

Many Thanks

Ben Wood (Cefas)
Apprentice Engineer
Pakefield Road, Lowestoft, Suffolk, NR331 0HT, UK
Email: ben.wood@cefas.co.uk<mailto:ben.wood@cefas.co.uk>
[signature footer]

**Comment by Billwilliams1952** [comment]
Version 0.2 is on Github. It ‘should’ work with Python 2.7.13 or Python 3.5.3. 

Good luck and please give me feedback on issues/problems/suggestions. 

Bill

**Comment by benwood19** [comment]
Thank you for doing the updates they work very well and I am having a large amount of success using this app. I was wondering if you may add a feature that adds an overlay onto the video/photos captured. Such as GPS, or even RTC data. or may already know a way of doing this? however, the time stamped files are a useful alternative. I think a lot of people have been waiting for a RPi camera GUI like this for a very long time and this does every job it needs too really. :)

Ben

**Comment by Billwilliams1952** [comment]
Thanks for your comments!

You can add text, time stamp, and frame number to the overlay, image, videos. As to GPS, this could be added but I would need info on where/how the GPS data is obtained. Can you give me more info?

Bill

**Comment by benwood19** [comment]
No problem,

One option I know of is that adafruit produce a board that is compatible with the raspberry pi that is called their GPS breakout board. So I don't know whether the data coming from that could be read by the Pi and implemented into the App. Or another possibility I was looking at was using a GNSS antenna to produce a raw NAV string that could then be fed into the raspberry pi using a serial port and that data then transferred into the App, however this is a more complex option.

Thanks
Ben

**Comment by Billwilliams1952** [comment]
Ok, I can look into an interface that you could use that would read the GPS data and output it to the video/image and/or save into the EXIF metadata (for JPEG  images)

Give me a bit to think about it. 

Bill

**Comment by vidapp** [comment]
Having some issues getting this to work with PiCam v2 and RPi 3 B+. Any new info on this configuration ? Cant wait to test!

**Comment by Billwilliams1952** [comment]
Hi Jake,

Can you provide more info on your problems?

Bill

**Comment by thiagogalvao** [comment]
Hi @vidapp,  try these commands:

1. sudo pip3 install pillow --upgrade

2. sudo python3 PiCameraApp.py

I had some issues on RPi 3  B+ to install imagetk, after upgrade the pillow with pip3 the problem was solved.

**Comment by FXRer** [comment]
Hello,
I'd like to know if any restriction in terms camera types, please? I'm using Logitech C920 and have following problem:

```
$ sudo python PiCameraApp.py
running....
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Error creating PiCamera instance! Shutting down.

Press any key...
```

```
$ sudo python3 PiCameraApp.py
running....
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Error creating PiCamera instance! Shutting down.

Press any key...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 633, in __init__
    prefix="Failed to create MMAL component %s" % self.component_type)
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PiCameraApp.py", line 1115, in Run
    camera = picamera.PiCamera(sensor_mode=1)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 460, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PiCameraApp.py", line 1130, in <module>
    Run()
  File "PiCameraApp.py", line 1119, in Run
    raw_input()
NameError: name 'raw_input' is not defined
```
System Info: RPi 3 + Raspbian Stretch 2018-06-27.

Thanks,

**Comment by Billwilliams1952** [comment]
Hi,

The PiCameraApp only works with the RPI camera module (currently versions V1 or V2). 

Bill

**Comment by dmeylman** [comment]
@Billwilliams1952  --Very nice, useful and professional looking gui for rpi camera. Just want to know if time stamp can be displayed at the bottom of frame (just curious, no problem at all). Again, great App. Thanks for sharing.

**Comment by robin-weaver** [comment]
Hi, having issues running the app. Was initially the tk module but now it isn't detecting the picamera module for some reason? 
ImportError: you do not seem to have picamera installed

I definitely do, and have run the test they recommend on their documentation:
python -c "import picamera" 
With no errors

**Comment by robin-weaver** [comment]
> Hi, having issues running the app. Was initially the tk module but now it isn't detecting the picamera module for some reason?
> ImportError: you do not seem to have picamera installed
> 
> I definitely do, and have run the test they recommend on their documentation:
> python -c "import picamera"
> With no errors

PSA: figured a few things out
1- You have to install picamera via apt install, it won't work if you do it via pip
2- if you're getting the error of certain assets not being there, make sure you are in the source directory (which is actually in the readme but easy to miss)

**Comment by Experiment4** [comment]
> Hi, having issues running the app. Was initially the tk module but now it isn't detecting the picamera module for some reason?
> ImportError: you do not seem to have picamera installed
> 
> I definitely do, and have run the test they recommend on their documentation:
> python -c "import picamera"
> With no errors
hi ozymandias,
i also encounter some problem running the app. 
my current startsetup is python3 /home/pi/PiCameraApp-master/Source/PiCameraApp.py
which leads to "Traceback (most recent call last):

> 
>   File "/home/pi/PiCameraApp-master/Source/AnnotationOverlay.py", line 61, in <module>
>     import 	picamera
> ModuleNotFoundError: No module named 'picamera'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/PiCameraApp-master/Source/PiCameraApp.py", line 38, in <module>
>     from	AnnotationOverlay	import *
>   File "/home/pi/PiCameraApp-master/Source/AnnotationOverlay.py", line 65, in <module>
>     raise ImportError("You do not seem to have picamera installed")
> ImportError: You do not seem to have picamera installed

and i do startup it from sourcedirectory.

You say
>  I definitely do, and have run the test they recommend on their documentation:
> python -c "import picamera"
> With no errors
where have you found that help ? do you have a link ? I am also not sure about PiCameraApp vs. picamera ...is it only some abreviation or is it a different name ...
cu
Thomas

**Comment by Experiment4** [comment]
pi@octopi:~/PiCameraApp-master/Source $ python3 -c PiCameraApp.py 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'PiCameraApp' is not defined
pi@octopi:~/PiCameraApp-master/Source $
