### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ho0tm** [Billwilliams1952/PiCameraApp#9]
Please Can u help me execute the code. each time i try to run the PiCameraApp.py file it gives me this : 
Traceback (most recent call last):
  File "PiCameraApp.py", line 38, in <module>
    from	AnnotationOverlay	import *
  File "/home/pi/Downloads/PiCameraApp-master/Source/AnnotationOverlay.py", line 52, in <module>
    from 	Dialog	import *
  File "/home/pi/Downloads/PiCameraApp-master/Source/Dialog.py", line 43, in <module>
    from PIL import Image, ImageTk, ExifTags
ImportError: cannot import name ImageTk

Whenever i try to run all the codes it gives errors like this. Please Help.

**Comment by Billwilliams1952** [comment]
You’re missing the ImageTk module. You need to install it.

**Comment by jsginkc** [comment]
I tried to install the App on Rspi 4 with Raspbian Buster lite but when I run the following command
To avoid errors I did the following: 

Installed PIL (Python Imaging Language) as a .tar.gz file

Then extracted this zipped file using
 
Tar xvfz Imaging-1.1.7.tar.gz
Then 
1.	Installed Python Imaging with Tkinter support:
sudo apt-get install python-imaging-tk
2.	sudo apt-get install python3-pil.imagetk
My problems seems to be that i am not understanding the PiCameraApp version 0.2 is not installing, also i think, me being novice at CLI, i am  trying to understand how will i start the application even if it is installed correctly 
3.	In the code: from PIL import ImageTk, Image ? you meant bring the .py from PIL and run it? I did the following and you will see the errors I am running into.
(this is the file or directory or Doc that i looked up in the tree and found and copied these in my current working drive) 
pi@raspberrypi:~/picameraapp$ dir
Image.py    Imaging-1.1.7         PiCameraApp.git
ImageTk.py  Imaging-1.1.7.tar.gz  PiCameraApp.py

pi@raspberrypi:~/picameraapp$ sudo python ImageTk.py
Traceback (most recent call last):
  File "ImageTk.py", line 28, in <module>
    import Tkinter, Image
  File "/home/pi/picameraapp/Image.py", line 69, in <module>
    import ImageMode
ImportError: No module named ImageMode

pi@raspberrypi:~/picameraapp$ sudo python Image.py
Traceback (most recent call last):
  File "Image.py", line 69, in <module>
    import ImageMode
ImportError: No module named ImageMode

pi@raspberrypi:~/picameraapp$ sudo python PiCameraApp.py (I tried this command using python3 also)
  File "PiCameraApp.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
pi@raspberrypi:~/picameraapp$

Question:
May be when you suggested 
_3.	In the code: from PIL import ImageTk, Image_ -  you meant to add some thing in the command sudo python PiCameraApp.py xxxxxx (that i am missing?)

If you can please put in the description on GitHub the step by step codes for full installation like 1. 2. 3.  I would appreciate! From reading other issues it seems like people have been able to install and run the app with success and are liking it.  

Comment:
Bill Can you please help! When i look at the GUI on GitHub I think yours is the best i have seen in this regard

Another Question:
Will this App help me change the picamera V2.1 output in any form i use it like in WebRTC etc and changes the setting and keeps it fixed/consistent in those applications?
